#!/bin/bash --login

# Exit automatically if any error escapes our capturing
# Also, print commands.  Since run-crons swallows output, good for debugging
set -e -x

#Source the settings
. /etc/emerge-sync.conf

#Decide if we are going to start knowing we have to send mail or not
if [ "$MAILFAILUREONLY" = "true" ]; then
	DOMAIL="false"
else
	DOMAIL="true"
fi

rm -f "${TMPFILE}"

# For verbose text
vecho () {
	if [ "$VERBOSE" = "true" ]; then
		echo "`date '+%x %X'`"  "$1" >> "${TMPFILE}"
	fi
	}

vecho "start to updates"

vecho "sync to gentoo repositories"
emerge --sync -q

# Apparently not a thing anymore
#vecho "GLSAs first"
#emerge -uDN @glsa

vecho "start update to all packages"
emerge -quDN @world

#If kernel checking/building enabled, do it here
if [ "$CHECKKERNEL" = "true" ]; then
	#INSTALLEDRAW=`equery -q l -F '$name: $version' 'sys-kernel/*' | grep sources`
	#INSTALLEDPKG=`echo "${INSTALLEDRAW}" | grep sources | awk -F : '{print $1}'`
	#INSTALLEDVER=`echo "${INSTALLEDRAW}" | grep sources | awk -F : '{print $2}'`
	INSTALLEDVER=`eselect kernel show | head -n -1 | tail -n 1 |  cut -d/ -f 4- | cut -d- -f 2-`
	RUNNINGVER=`uname -r | awk -F - '{print $1}'`
	
	if [ "${INSTALLEDVER}" = "${RUNNINGVER}" ]; then
		if [ "$UPDATEKERNEL" = "true" ]; then
			echo "**AUTOUPDATING KERNEL**"
			cd /usr/src/linux #where we want to be
			make clean # clean up for sanity

			#Remove anything laying about
			rm .config

			#Copy in previous config TODO: use default if unable to copy?
			gzip -dc /proc/config.gz > .config || cp /usr/src/linux-`uname -r`/.config . || (echo "Could not copy old kernel config"; break)

			#decide between genkernel and "manual"
			if [ `which genkernel` -a -x `which genkernel` ]; then
				genkernel --oldconfig --kernel-config=.config all || die "Genkernel failed!"
			else
				make modules_prepare || die "Modules_prepare failed with $?"
				emerge @module-rebuild || die "Modules rebuild failed with $?"
				make -j5 || die "Build failed with $?"
				make modules_install || die "Module installation failed with $?"
				# Will update symlinks so bootloader uses new kernel
				make install || die "Install failed with $?" 
			fi
			echo "**KERNEL UPDATE PERFORMED, CONSIDER REBOOT**"
		else
			echo "** KERNEL UPDATE AVAILABLE **"
		fi
	fi
fi

#We check this each time.  It doesnt take much time and covers a whole multitude of possibilites
vecho "Rebuild modules"
emerge -quDN @module-rebuild

if [ `which python-updater` -a -x `which python-updater` ]; then
	vecho "Rebuild python packages which require it"
	python-updater
else
	vecho "python-updater not installed, not rebuilding python packages which require it.  Emerge python-updater to run"
fi

if [ `which perl-cleaner` -a -x `which perl-cleaner` ]; then
	vecho "Rebuild perl modules which require it"
	perl-cleaner --all
else
	vecho "perl-cleaner not installed, not rebuilding modules that require rebuilding.  Emerge 'perl-cleaner' to run this step."
fi

vecho "rebuilding packages which require it"
revdep-rebuild -q

vecho "The following packages are unused and could be removed."
emerge -qp --depclean

vecho "Autoupdating config"
etc-update -p -q

vecho "Finally, news:"
eselect news read --quiet new

vecho "emerge-sync ran successfully"

